from django.urls import path

from .views import (
    PreparationCancelView,
    PreparationCollectionView,
    PreparationDetailView,
    PreparationResultFileView,
    ResourceCollectionView,
    ResourceDetailView,
    ResourceFileView,
    SearchView,
    QuizAttemptView,
    FlashcardReviewView,
    StudentFlashcardReviewView,
    StudentPreparationCancelView,
    StudentPreparationCollectionView,
    StudentPreparationDetailView,
    StudentPreparationResultFileView,
    StudentQuizAttemptView,
    StudentResourceCollectionView,
    StudentResourceDetailView,
    StudentResourceFileView,
    StudentSearchView,
    StudentUploadView,
    TeacherFlashcardReviewView,
    TeacherPreparationCancelView,
    TeacherPreparationCollectionView,
    TeacherPreparationDetailView,
    TeacherPreparationResultFileView,
    TeacherQuizAttemptView,
    TeacherResourceCollectionView,
    TeacherResourceDetailView,
    TeacherResourceFileView,
    TeacherSearchView,
    TeacherUploadView,
    UploadView,
)

app_name = "learning"

urlpatterns = [
    path("search/", SearchView.as_view(), name="search"),
    path("resources/", ResourceCollectionView.as_view(), name="resources"),
    path("resources/upload/", UploadView.as_view(), name="upload"),
    path("resources/<uuid:resource_id>/", ResourceDetailView.as_view(), name="resource-detail"),
    path("resources/<uuid:resource_id>/file/", ResourceFileView.as_view(), name="resource-file"),
    path("preparations/", PreparationCollectionView.as_view(), name="preparations"),
    path("preparations/<uuid:preparation_id>/", PreparationDetailView.as_view(), name="preparation-detail"),
    path("preparations/<uuid:preparation_id>/cancel/", PreparationCancelView.as_view(), name="preparation-cancel"),
    path("preparations/<uuid:preparation_id>/result-file/", PreparationResultFileView.as_view(), name="preparation-result-file"),
    path("preparations/<uuid:preparation_id>/attempts/", QuizAttemptView.as_view(), name="preparation-attempts"),
    path("preparations/<uuid:preparation_id>/reviews/", FlashcardReviewView.as_view(), name="preparation-reviews"),
    path("quizzes/<uuid:preparation_id>/attempts/", QuizAttemptView.as_view(), name="quiz-attempts"),
    path("flashcards/<uuid:preparation_id>/reviews/", FlashcardReviewView.as_view(), name="flashcard-reviews"),
    path("teacher/search/", TeacherSearchView.as_view(), name="teacher-search"),
    path("teacher/resources/", TeacherResourceCollectionView.as_view(), name="teacher-resources"),
    path("teacher/resources/upload/", TeacherUploadView.as_view(), name="teacher-upload"),
    path("teacher/resources/<uuid:resource_id>/", TeacherResourceDetailView.as_view(), name="teacher-resource-detail"),
    path("teacher/resources/<uuid:resource_id>/file/", TeacherResourceFileView.as_view(), name="teacher-resource-file"),
    path("teacher/preparations/", TeacherPreparationCollectionView.as_view(), name="teacher-preparations"),
    path("teacher/preparations/<uuid:preparation_id>/", TeacherPreparationDetailView.as_view(), name="teacher-preparation-detail"),
    path("teacher/preparations/<uuid:preparation_id>/cancel/", TeacherPreparationCancelView.as_view(), name="teacher-preparation-cancel"),
    path("teacher/preparations/<uuid:preparation_id>/result-file/", TeacherPreparationResultFileView.as_view(), name="teacher-preparation-result-file"),
    path("teacher/preparations/<uuid:preparation_id>/attempts/", TeacherQuizAttemptView.as_view(), name="teacher-preparation-attempts"),
    path("teacher/preparations/<uuid:preparation_id>/reviews/", TeacherFlashcardReviewView.as_view(), name="teacher-preparation-reviews"),
    path("student/search/", StudentSearchView.as_view(), name="student-search"),
    path("student/resources/", StudentResourceCollectionView.as_view(), name="student-resources"),
    path("student/resources/upload/", StudentUploadView.as_view(), name="student-upload"),
    path("student/resources/<uuid:resource_id>/", StudentResourceDetailView.as_view(), name="student-resource-detail"),
    path("student/resources/<uuid:resource_id>/file/", StudentResourceFileView.as_view(), name="student-resource-file"),
    path("student/preparations/", StudentPreparationCollectionView.as_view(), name="student-preparations"),
    path("student/preparations/<uuid:preparation_id>/", StudentPreparationDetailView.as_view(), name="student-preparation-detail"),
    path("student/preparations/<uuid:preparation_id>/cancel/", StudentPreparationCancelView.as_view(), name="student-preparation-cancel"),
    path("student/preparations/<uuid:preparation_id>/result-file/", StudentPreparationResultFileView.as_view(), name="student-preparation-result-file"),
    path("student/preparations/<uuid:preparation_id>/attempts/", StudentQuizAttemptView.as_view(), name="student-preparation-attempts"),
    path("student/preparations/<uuid:preparation_id>/reviews/", StudentFlashcardReviewView.as_view(), name="student-preparation-reviews"),
    path("student/quizzes/<uuid:preparation_id>/attempts/", StudentQuizAttemptView.as_view(), name="student-quiz-attempts"),
    path("student/flashcards/<uuid:preparation_id>/reviews/", StudentFlashcardReviewView.as_view(), name="student-flashcard-reviews"),
]
