# Generated by Django 6.1.1 on 2026-10-05 12:45

import apps.learning.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('txt', 'Text'), ('docx', 'Word document'), ('external', 'External resource')], max_length=12)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('external', 'External'), ('generated', 'Generated')], default='upload', max_length=12)),
                ('file', models.FileField(blank=True, upload_to=apps.learning.models.private_resource_path)),
                ('processed_text_file', models.FileField(blank=True, upload_to=apps.learning.models.private_text_path)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_provider', models.CharField(blank=True, max_length=64)),
                ('license_name', models.CharField(blank=True, max_length=120)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=12)),
                ('processing_error', models.TextField(blank=True)),
                ('resource_version', models.PositiveIntegerField(default=1)),
                ('processor_version', models.CharField(default='extract-1', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_version', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='learning.learningresource')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='PreparationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preparation_type', models.CharField(choices=[('quiz', 'Quiz'), ('short_note', 'Short Note'), ('flashcard', 'Flashcard'), ('image', 'Image'), ('animation', 'Animation')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('generator_version', models.CharField(default='generator-1', max_length=32)),
                ('prompt_version', models.CharField(default='source-template-1', max_length=32)),
                ('model_name', models.CharField(default='source-grounded-local', max_length=120)),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='learning.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='learning_le_owner_i_9f73d9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningchunk',
            index=models.Index(fields=['resource', 'resource_version'], name='learning_le_resourc_d69bc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningchunk',
            constraint=models.UniqueConstraint(fields=('resource', 'resource_version', 'index'), name='learning_chunk_version_index_uniq'),
        ),
        migrations.AddIndex(
            model_name='preparationrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='learning_pr_user_id_2cd3a4_idx'),
        ),
    ]
