# Generated by Django 6.1.1 on 2026-10-05 13:42

import apps.learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_preparationrequest_result_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='file',
            field=models.FileField(blank=True, max_length=512, upload_to=apps.learning.models.private_resource_path),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='processed_text_file',
            field=models.FileField(blank=True, max_length=512, upload_to=apps.learning.models.private_text_path),
        ),
        migrations.AlterField(
            model_name='preparationrequest',
            name='result_file',
            field=models.FileField(blank=True, max_length=512, upload_to=apps.learning.models.private_result_path),
        ),
    ]
