# Generated by Django 6.1.1 on 2026-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_learningresource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationrequest',
            name='preparation_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('short_note', 'Short Note'), ('flashcard', 'Flashcard'), ('image', 'Image'), ('animation', 'Animation'), ('other', 'Other')], max_length=16),
        ),
    ]
